// Generated by gen_lua_api.py — do not edit.
#include "lua_api_fn.h"
#include "lua_bind_util.h"

#include "game_kit/ai_state.h"
#include "game_kit/anim_player.h"
#include "game_kit/audio_mixer.h"
#include "game_kit/level_flow.h"
#include "game_kit/nav.h"
#include "game_kit/runtime.h"
#include "game_kit/snapshot.h"
#include "game_kit/timeline.h"

#include "engine/core/log.h"
#include "engine/core/math.h"
#include "engine/input/input_system.h"
#include "engine/media/media.h"
#include "engine/scene/world.h"
#include "engine/ui/retained_ui.h"

#include <cstdint>
#include <string>

#if defined(GAME_KIT_WITH_LUA) && GAME_KIT_WITH_LUA
extern "C" {
#include "lauxlib.h"
#include "lua.h"
}

namespace game_kit {
int LLog(lua_State* L) {
  engine::LogInfo(luaL_checkstring(L, 1));
  return 0;
}

int LSetPos(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->world) {
    lua_pushboolean(L, 0);
    return 1;
  }
  int arg = 1;
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
    arg = 2;
  }
  const float x = static_cast<float>(luaL_checknumber(L, arg));
  const float y = static_cast<float>(luaL_checknumber(L, arg + 1));
  const float z = static_cast<float>(luaL_checknumber(L, arg + 2));
  const auto node = NodeOf(h, name);
  if (node == engine::scene::kInvalidNode || !h->world->valid(node)) {
    lua_pushboolean(L, 0);
    return 1;
  }
  auto t = h->world->local_transform(node);
  t.position = {x, y, z};
  h->world->set_local_transform(node, t);
  lua_pushboolean(L, 1);
  return 1;
}

int LGetPos(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->world) {
    return 0;
  }
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
  }
  const auto node = NodeOf(h, name);
  if (node == engine::scene::kInvalidNode || !h->world->valid(node)) {
    return 0;
  }
  const auto& t = h->world->local_transform(node);
  lua_pushnumber(L, t.position.x);
  lua_pushnumber(L, t.position.y);
  lua_pushnumber(L, t.position.z);
  return 3;
}

int LSetRot(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->world) {
    lua_pushboolean(L, 0);
    return 1;
  }
  int arg = 1;
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
    arg = 2;
  }
  const float yaw = static_cast<float>(luaL_checknumber(L, arg));
  const float pitch = static_cast<float>(luaL_optnumber(L, arg + 1, 0.0));
  const float roll = static_cast<float>(luaL_optnumber(L, arg + 2, 0.0));
  const auto node = NodeOf(h, name);
  if (node == engine::scene::kInvalidNode || !h->world->valid(node)) {
    lua_pushboolean(L, 0);
    return 1;
  }
  auto t = h->world->local_transform(node);
  t.rotation = engine::Quat::FromEulerYxz(yaw, pitch, roll);
  h->world->set_local_transform(node, t);
  lua_pushboolean(L, 1);
  return 1;
}

int LGetRot(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->world) {
    return 0;
  }
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
  }
  const auto node = NodeOf(h, name);
  if (node == engine::scene::kInvalidNode || !h->world->valid(node)) {
    return 0;
  }
  const auto& r = h->world->local_transform(node).rotation;
  lua_pushnumber(L, r.x);
  lua_pushnumber(L, r.y);
  lua_pushnumber(L, r.z);
  lua_pushnumber(L, r.w);
  return 4;
}

int LSetScale(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->world) {
    lua_pushboolean(L, 0);
    return 1;
  }
  int arg = 1;
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
    arg = 2;
  }
  const float x = static_cast<float>(luaL_checknumber(L, arg));
  const float y = static_cast<float>(luaL_optnumber(L, arg + 1, x));
  const float z = static_cast<float>(luaL_optnumber(L, arg + 2, x));
  const auto node = NodeOf(h, name);
  if (node == engine::scene::kInvalidNode || !h->world->valid(node)) {
    lua_pushboolean(L, 0);
    return 1;
  }
  auto t = h->world->local_transform(node);
  t.scale = {x, y, z};
  h->world->set_local_transform(node, t);
  lua_pushboolean(L, 1);
  return 1;
}

int LGetScale(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->world) {
    return 0;
  }
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
  }
  const auto node = NodeOf(h, name);
  if (node == engine::scene::kInvalidNode || !h->world->valid(node)) {
    return 0;
  }
  const auto& s = h->world->local_transform(node).scale;
  lua_pushnumber(L, s.x);
  lua_pushnumber(L, s.y);
  lua_pushnumber(L, s.z);
  return 3;
}

int LSetVisible(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->world) {
    lua_pushboolean(L, 0);
    return 1;
  }
  int arg = 1;
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING && lua_type(L, 2) != LUA_TNONE && lua_gettop(L) >= 2 &&
      (lua_type(L, 2) == LUA_TBOOLEAN || lua_type(L, 2) == LUA_TNUMBER)) {
    name = lua_tostring(L, 1);
    arg = 2;
  }
  const bool vis = lua_toboolean(L, arg) != 0;
  const auto node = NodeOf(h, name);
  if (node == engine::scene::kInvalidNode || !h->world->valid(node)) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->world->set_visible(node, vis);
  lua_pushboolean(L, 1);
  return 1;
}

int LGetChildren(lua_State* L) {
  auto* h = Host(L);
  lua_newtable(L);
  if (!h || !h->world) {
    return 1;
  }
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
  }
  const auto node = NodeOf(h, name);
  if (node == engine::scene::kInvalidNode || !h->world->valid(node)) {
    return 1;
  }
  int i = 1;
  for (auto ch : h->world->children(node)) {
    lua_pushstring(L, h->world->name(ch).c_str());
    lua_rawseti(L, -2, i++);
  }
  return 1;
}

int LDestroyEntity(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    lua_pushboolean(L, 0);
    return 1;
  }
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
  }
  Entity* e = EntityOf(h, name);
  if (!e) {
    lua_pushboolean(L, 0);
    return 1;
  }
  if (h->world && e->node != engine::scene::kInvalidNode && h->world->valid(e->node)) {
    (void)h->world->DestroyNode(e->node);
  }
  h->rt->entities().Destroy(e->id);
  lua_pushboolean(L, 1);
  return 1;
}

int LInstantiate(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    lua_pushboolean(L, 0);
    return 1;
  }
  const char* id = luaL_checkstring(L, 1);
  engine::scene::Transform t;
  t.position.x = static_cast<float>(luaL_optnumber(L, 2, 0.0));
  t.position.y = static_cast<float>(luaL_optnumber(L, 3, 0.0));
  t.position.z = static_cast<float>(luaL_optnumber(L, 4, 0.0));
  const auto node = h->rt->SpawnPrefab(id, t);
  lua_pushboolean(L, node != engine::scene::kInvalidNode);
  return 1;
}

int LCurrentLevel(lua_State* L) {
  auto* h = Host(L);
  lua_pushstring(L, (h && h->rt) ? h->rt->levels().current().c_str() : "");
  return 1;
}

int LPublish(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    return 0;
  }
  h->rt->events().Publish(luaL_checkstring(L, 1), luaL_optstring(L, 2, ""));
  return 0;
}

int LCancelTimer(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->timer().Cancel(static_cast<std::uint32_t>(luaL_checkinteger(L, 1)));
  }
  return 0;
}

int LUnsubscribe(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->events().Unsubscribe(static_cast<std::uint32_t>(luaL_checkinteger(L, 1)));
  }
  return 0;
}

int LSetPaused(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->set_paused(lua_toboolean(L, 1) != 0);
  }
  return 0;
}

int LSetTimeScale(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->set_time_scale(static_cast<float>(luaL_checknumber(L, 1)));
  }
  return 0;
}

int LGetTimeScale(lua_State* L) {
  auto* h = Host(L);
  lua_pushnumber(L, (h && h->rt) ? h->rt->time_scale() : 1.0);
  return 1;
}

int LKeyDown(lua_State* L) {
  auto* in = InputOf(Host(L));
  if (!in) {
    lua_pushboolean(L, 0);
    return 1;
  }
  const auto key = ParseKey(luaL_checkstring(L, 1));
  lua_pushboolean(L, in->key_down(key) ? 1 : 0);
  return 1;
}

int LAxis(lua_State* L) {
  auto* in = InputOf(Host(L));
  if (!in) {
    lua_pushnumber(L, 0);
    return 1;
  }
  lua_pushnumber(L, in->axis(luaL_checkstring(L, 1)));
  return 1;
}

int LPressed(lua_State* L) {
  auto* in = InputOf(Host(L));
  if (!in) {
    lua_pushboolean(L, 0);
    return 1;
  }
  lua_pushboolean(L, in->pressed(luaL_checkstring(L, 1)) ? 1 : 0);
  return 1;
}

int LUiSetText(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->ui()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->ui()->set_text(luaL_checkstring(L, 1), luaL_checkstring(L, 2));
  lua_pushboolean(L, 1);
  return 1;
}

int LUiSetVisible(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->ui()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->ui()->set_visible(luaL_checkstring(L, 1), lua_toboolean(L, 2) != 0);
  lua_pushboolean(L, 1);
  return 1;
}

int LUiLabel(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->ui()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->ui()->Label(luaL_checkstring(L, 1), luaL_optstring(L, 2, ""),
                     static_cast<float>(luaL_optnumber(L, 3, 16.0)),
                     static_cast<float>(luaL_optnumber(L, 4, 16.0)));
  lua_pushboolean(L, 1);
  return 1;
}

int LUiButton(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->ui()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->ui()->Button(luaL_checkstring(L, 1), luaL_optstring(L, 2, "OK"),
                      static_cast<float>(luaL_optnumber(L, 3, 16.0)),
                      static_cast<float>(luaL_optnumber(L, 4, 48.0)),
                      static_cast<float>(luaL_optnumber(L, 5, 80.0)),
                      static_cast<float>(luaL_optnumber(L, 6, 24.0)));
  lua_pushboolean(L, 1);
  return 1;
}

int LUiPanel(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->ui()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->ui()->Panel(luaL_checkstring(L, 1), static_cast<float>(luaL_optnumber(L, 2, 16.0)),
                     static_cast<float>(luaL_optnumber(L, 3, 16.0)),
                     static_cast<float>(luaL_optnumber(L, 4, 280.0)),
                     static_cast<float>(luaL_optnumber(L, 5, 120.0)));
  lua_pushboolean(L, 1);
  return 1;
}

int LUiToggle(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->ui()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->ui()->Toggle(luaL_checkstring(L, 1), luaL_optstring(L, 2, ""),
                      static_cast<float>(luaL_optnumber(L, 3, 16.0)),
                      static_cast<float>(luaL_optnumber(L, 4, 16.0)),
                      static_cast<float>(luaL_optnumber(L, 5, 80.0)),
                      static_cast<float>(luaL_optnumber(L, 6, 22.0)), lua_toboolean(L, 7) != 0);
  lua_pushboolean(L, 1);
  return 1;
}

int LUiSlider(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->ui()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->ui()->Slider(luaL_checkstring(L, 1), luaL_optstring(L, 2, ""),
                      static_cast<float>(luaL_optnumber(L, 3, 16.0)),
                      static_cast<float>(luaL_optnumber(L, 4, 16.0)),
                      static_cast<float>(luaL_optnumber(L, 5, 160.0)),
                      static_cast<float>(luaL_optnumber(L, 6, 18.0)),
                      static_cast<float>(luaL_optnumber(L, 7, 0.0)),
                      static_cast<float>(luaL_optnumber(L, 8, 0.0)),
                      static_cast<float>(luaL_optnumber(L, 9, 1.0)));
  lua_pushboolean(L, 1);
  return 1;
}

int LUiLayout(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->ui()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->ui()->LayoutColumn(luaL_checkstring(L, 1), static_cast<float>(luaL_optnumber(L, 2, 8.0)));
  lua_pushboolean(L, 1);
  return 1;
}

int LStopAudio(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt && h->rt->audio()) {
    h->rt->audio()->StopAll();
    lua_pushboolean(L, 1);
    return 1;
  }
  lua_pushboolean(L, 0);
  return 1;
}

int LAssetReady(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    lua_pushboolean(L, 0);
    return 1;
  }
  const auto* handle = h->rt->FindAsset(luaL_checkstring(L, 1));
  lua_pushboolean(L, handle && handle->is_ready() ? 1 : 0);
  return 1;
}

int LSetAi(lua_State* L) {
  auto* h = Host(L);
  if (!h) {
    lua_pushboolean(L, 0);
    return 1;
  }
  std::string name;
  int arg = 1;
  if (lua_type(L, 1) == LUA_TSTRING && lua_gettop(L) >= 2) {
    name = lua_tostring(L, 1);
    arg = 2;
  }
  Entity* e = EntityOf(h, name);
  if (!e) {
    lua_pushboolean(L, 0);
    return 1;
  }
  e->ai.Set(ParseAiState(luaL_checkstring(L, arg)));
  lua_pushboolean(L, 1);
  return 1;
}

int LGetAi(lua_State* L) {
  auto* h = Host(L);
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
  }
  Entity* e = EntityOf(h, name);
  lua_pushstring(L, e ? ToString(e->ai.state).data() : "Idle");
  return 1;
}

int LStopAnim(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    return 0;
  }
  std::string name;
  if (lua_type(L, 1) == LUA_TSTRING) {
    name = lua_tostring(L, 1);
  }
  Entity* e = EntityOf(h, name);
  if (e) {
    h->rt->anims().GetOrCreate(e->name).Stop();
  }
  return 0;
}

int LAnimTrigger(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    lua_pushboolean(L, 0);
    return 1;
  }
  std::string name;
  int arg = 1;
  if (lua_type(L, 1) == LUA_TSTRING && lua_gettop(L) >= 2) {
    name = lua_tostring(L, 1);
    arg = 2;
  }
  Entity* e = EntityOf(h, name);
  if (!e) {
    lua_pushboolean(L, 0);
    return 1;
  }
  h->rt->anims().GetOrCreate(e->name).SetTrigger(luaL_checkstring(L, arg));
  lua_pushboolean(L, 1);
  return 1;
}

int LAddTag(lua_State* L) {
  auto* h = Host(L);
  std::string name;
  int arg = 1;
  if (lua_type(L, 1) == LUA_TSTRING && lua_gettop(L) >= 2) {
    name = lua_tostring(L, 1);
    arg = 2;
  }
  Entity* e = EntityOf(h, name);
  if (!e) {
    lua_pushboolean(L, 0);
    return 1;
  }
  e->AddTag(luaL_checkstring(L, arg));
  lua_pushboolean(L, 1);
  return 1;
}

int LHasTag(lua_State* L) {
  auto* h = Host(L);
  std::string name;
  int arg = 1;
  if (lua_type(L, 1) == LUA_TSTRING && lua_gettop(L) >= 2) {
    name = lua_tostring(L, 1);
    arg = 2;
  }
  Entity* e = EntityOf(h, name);
  lua_pushboolean(L, e && e->HasTag(luaL_checkstring(L, arg)) ? 1 : 0);
  return 1;
}

int LFindByTag(lua_State* L) {
  auto* h = Host(L);
  lua_newtable(L);
  if (!h || !h->rt) {
    return 1;
  }
  const char* tag = luaL_checkstring(L, 1);
  int i = 1;
  for (Entity* e : h->rt->entities().FindByTag(tag)) {
    lua_pushstring(L, e->name.c_str());
    lua_rawseti(L, -2, i++);
  }
  return 1;
}

int LSteer(lua_State* L) {
  auto* h = Host(L);
  engine::Vec3 from{static_cast<float>(luaL_checknumber(L, 1)),
                    static_cast<float>(luaL_checknumber(L, 2)),
                    static_cast<float>(luaL_checknumber(L, 3))};
  engine::Vec3 goal{static_cast<float>(luaL_checknumber(L, 4)),
                    static_cast<float>(luaL_checknumber(L, 5)),
                    static_cast<float>(luaL_checknumber(L, 6))};
  const float speed = static_cast<float>(luaL_checknumber(L, 7));
  const float dt = static_cast<float>(luaL_checknumber(L, 8));
  engine::Vec3 n = from;
  if (h && h->rt) {
    n = h->rt->nav().Steer(from, goal, speed, dt);
  }
  lua_pushnumber(L, n.x);
  lua_pushnumber(L, n.y);
  lua_pushnumber(L, n.z);
  return 3;
}

int LAddNavObstacle(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->nav().AddObstacle(
        {static_cast<float>(luaL_checknumber(L, 1)), static_cast<float>(luaL_checknumber(L, 2)),
         static_cast<float>(luaL_checknumber(L, 3))},
        {static_cast<float>(luaL_optnumber(L, 4, 0.5)), static_cast<float>(luaL_optnumber(L, 5, 0.5)),
         static_cast<float>(luaL_optnumber(L, 6, 0.5))});
  }
  return 0;
}

int LSetSense(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->nav().SetSense(luaL_checkstring(L, 1), luaL_checkstring(L, 2),
                          static_cast<float>(luaL_checknumber(L, 3)));
  }
  return 0;
}

int LBakeNav(lua_State* L) {
  auto* h = Host(L);
  lua_pushboolean(L, (h && h->rt && h->rt->nav().BakeFromObstacles()) ? 1 : 0);
  return 1;
}

int LTimelineAdd(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->timeline().Add(static_cast<float>(luaL_checknumber(L, 1)), luaL_checkstring(L, 2),
                          luaL_optstring(L, 3, ""));
  }
  return 0;
}

int LTimelinePlay(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->timeline().Play();
  }
  return 0;
}

int LTimelineStop(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->timeline().Stop();
  }
  return 0;
}

int LTimelinePause(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->timeline().Pause();
  }
  return 0;
}

int LTimelineSeek(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->timeline().Seek(static_cast<float>(luaL_checknumber(L, 1)));
  }
  return 0;
}

int LSaveSnapshot(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    lua_pushboolean(L, 0);
    return 1;
  }
  const int slot = static_cast<int>(luaL_checkinteger(L, 1));
  const auto snap = CaptureSnapshot(*h->rt, h->world);
  lua_pushboolean(L, SaveSnapshot(h->rt->saves(), slot, snap).ok() ? 1 : 0);
  return 1;
}

int LLoadSnapshot(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    lua_pushboolean(L, 0);
    return 1;
  }
  auto loaded = LoadSnapshot(h->rt->saves(), static_cast<int>(luaL_checkinteger(L, 1)));
  if (!loaded) {
    lua_pushboolean(L, 0);
    return 1;
  }
  lua_pushboolean(L, ApplySnapshot(*h->rt, h->world, loaded.value()).ok() ? 1 : 0);
  return 1;
}

int LReplicatePush(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->replicator().Push(CaptureSnapshot(*h->rt, h->world));
  }
  return 0;
}

int LReplicatePull(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt || !h->rt->replicator().has()) {
    lua_pushboolean(L, 0);
    return 1;
  }
  lua_pushboolean(L, ApplySnapshot(*h->rt, h->world, h->rt->replicator().Pull()).ok() ? 1 : 0);
  return 1;
}

int LReplicatePushDiff(lua_State* L) {
  auto* h = Host(L);
  if (h && h->rt) {
    h->rt->replicator().PushDiff(CaptureSnapshot(*h->rt, h->world));
  }
  return 0;
}

int LUnloadLevel(lua_State* L) {
  auto* h = Host(L);
  if (!h || !h->rt) {
    lua_pushboolean(L, 0);
    return 1;
  }
  const auto st = h->rt->levels().UnloadStacked(luaL_checkstring(L, 1), h->rt->app(), *h->rt);
  lua_pushboolean(L, st.ok() ? 1 : 0);
  return 1;
}

int LSetBudget(lua_State* L) {
  auto* h = Host(L);
  if (h && h->vm) {
    h->vm->set_instruction_budget(static_cast<int>(luaL_checkinteger(L, 1)));
  }
  return 0;
}
}  // namespace game_kit
#endif
