#pragma once
// Generated by gen_lua_api.py — do not edit.

#if defined(GAME_KIT_WITH_LUA) && GAME_KIT_WITH_LUA
extern "C" {
#include "lua.h"
}

namespace game_kit {

int LLog(lua_State* L);
int LImport(lua_State* L);
int LSetPos(lua_State* L);
int LGetPos(lua_State* L);
int LSetRot(lua_State* L);
int LGetRot(lua_State* L);
int LSetScale(lua_State* L);
int LGetScale(lua_State* L);
int LSetVisible(lua_State* L);
int LGetChildren(lua_State* L);
int LDestroyEntity(lua_State* L);
int LInstantiate(lua_State* L);
int LRequestLevel(lua_State* L);
int LCurrentLevel(lua_State* L);
int LPublish(lua_State* L);
int LDelay(lua_State* L);
int LInterval(lua_State* L);
int LCancelTimer(lua_State* L);
int LSubscribe(lua_State* L);
int LUnsubscribe(lua_State* L);
int LSetPaused(lua_State* L);
int LSetTimeScale(lua_State* L);
int LGetTimeScale(lua_State* L);
int LKeyDown(lua_State* L);
int LAxis(lua_State* L);
int LPressed(lua_State* L);
int LRaycast(lua_State* L);
int LUiSetText(lua_State* L);
int LUiSetVisible(lua_State* L);
int LUiLabel(lua_State* L);
int LUiButton(lua_State* L);
int LUiPanel(lua_State* L);
int LUiToggle(lua_State* L);
int LUiSlider(lua_State* L);
int LUiLayout(lua_State* L);
int LPlayWav(lua_State* L);
int LStopAudio(lua_State* L);
int LRequestLoad(lua_State* L);
int LAssetReady(lua_State* L);
int LSetAi(lua_State* L);
int LGetAi(lua_State* L);
int LPlayAnim(lua_State* L);
int LStopAnim(lua_State* L);
int LAnimNotify(lua_State* L);
int LAnimTrigger(lua_State* L);
int LAddTag(lua_State* L);
int LHasTag(lua_State* L);
int LFindByTag(lua_State* L);
int LSteer(lua_State* L);
int LAddNavObstacle(lua_State* L);
int LSetSense(lua_State* L);
int LSetPath(lua_State* L);
int LBakeNav(lua_State* L);
int LBakeNavWorld(lua_State* L);
int LFindPath(lua_State* L);
int LNavAgent(lua_State* L);
int LMixerPlay(lua_State* L);
int LMixerStop(lua_State* L);
int LMixerGain(lua_State* L);
int LTimelineAdd(lua_State* L);
int LTimelinePlay(lua_State* L);
int LTimelineStop(lua_State* L);
int LTimelinePause(lua_State* L);
int LTimelineSeek(lua_State* L);
int LSaveSnapshot(lua_State* L);
int LLoadSnapshot(lua_State* L);
int LReplicatePush(lua_State* L);
int LReplicatePull(lua_State* L);
int LReplicatePushDiff(lua_State* L);
int LUnloadLevel(lua_State* L);
int LSetBudget(lua_State* L);
int LWait(lua_State* L);
int LWaitEvent(lua_State* L);
int LStartCoroutine(lua_State* L);

}  // namespace game_kit
#endif
